apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus-nodes
  name: prometheus-nodes
spec:
  clusterIP: None
  ports:
    - port: 9100
      name: prom-exporter
  selector:
    name: prometheus-node
