apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus-nodes
  name: prometheus-nodes
spec:
  selector:
    name: prometheus-node
  clusterIP: None
  ports:
    - name: prom-exporter
      port: 9100
      protocol: TCP
