apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    version: v1
spec:
  selector:
    version: v1
    name: prometheus
  type: LoadBalancer
  ports:
  - name: prometheus
    port: 9090
    nodePort: 30200
    protocol: TCP
