global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9090']
  - job_name: 'k8s'
    scrape_interval: 5s
    dns_sd_configs:
      - type: SRV
        refresh_interval: 5s
        names:
          - _prom-exporter._tcp.prometheus-nodes
  - job_name: 'cassandra'
    scrape_interval: 30s
    dns_sd_configs:
      - type: SRV
        refresh_interval: 5s
        names:
          - _jmx-exporter._tcp.cassandra-peers

