apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      nodeSelector:
        name: cassandra
      containers:
        - image: localhost:30100/yagoda-jmx-exporter
          name: jmx-exporter
          env:
            - name: JMX_EXPORTER_PORT
              value: 9101
          ports:
            - containerPort: 9101
              name: jmx-exporter
          resources:
            request:
              cpu: 0.1
        - image: localhost:30100/yagoda-cassandra
          name: cassandra
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - name: CASSANDRA_DC
              value: DC1
            - name: CASSANDRA_RACK
              value: Kubernetes Cluster
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
          resources:
            request:
              cpu: 0.1
          volumeMounts:
            - mountPath: /var/lib/cassandra/data
              name: data
          readinessProbe:
            exec:
              command:
                - cqlsh
                - --execute
                - "HELP"
            initialDelaySeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - "/opt/yagoda/bin/cassandra-check"
            initialDelaySeconds: 30
            timeoutSeconds: 5
      restartPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
