# Headless service that allows us to get the IP addresses of our Cassandra nodes
apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra-peers
  name: cassandra-peers
spec:
  clusterIP: None
  ports:
    - port: 7000
      name: intra-node
    - port: 7001
      name: tls-intra
    - port: 9101
      name: jmx-exporter
  selector:
    name: cassandra
